data_dir:
  esc50: /project/shrikann_35/tiantiaf/ESC-50-master
  gtzan: /project/shrikann_35/tiantiaf/gtzan
  speechcommands: /project/shrikann_35/tiantiaf/audio-prompt-fl/raw-data/speech_commands_v0.02
project_dir: /scratch1/tiantiaf/audio-gen-quality